from __future__ import annotations

from core.phase_manager import Phase

ML_FAMILY_BEHAVIOR_ALIASES = {
    "ML-AUTH": {
        "normal": {"expected_auth_activity"},
        "suspicious": {"auth_attack_or_abuse", "brute_force_or_auth_attack"},
    },
    "ML-SUDO": {
        "normal": set(),
        "suspicious": {"sudo_escalation_or_root_access", "privilege_escalation_behavior"},
    },
    "ML-PROC": {
        "normal": {"routine_exec"},
        "suspicious": {"suspicious_process", "discovery_behavior", "lolbin_abuse"},
    },
    "ML-SERVICE": {
        "normal": set(),
        "suspicious": {"persistence_behavior", "persistence_service_mod"},
    },
    "ML-NET": {
        "normal": {"expected_outbound"},
        "suspicious": {"network_abuse"},
    },
    "ML-SEQ": {
        "normal": set(),
        "suspicious": {"lateral_movement_sequence", "suspicious_sequence"},
    },
    "ML-USER": {
        "normal": set(),
        "suspicious": {"user_behavior_anomaly"},
    },
    "ML-HOST": {
        "normal": set(),
        "suspicious": {"host_behavior_anomaly", "first_seen_behavior", "monitoring_or_host_drift"},
    },
    "ML-DBAUTH": {
        "normal": {"expected_db_activity"},
        "suspicious": {"db_login_abuse"},
    },
    "ML-DNS": {
        "normal": set(),
        "suspicious": {"dns_anomaly"},
    },
    "ML-WEBPOST": {
        "normal": set(),
        "suspicious": {"web_attack_or_post_exploit"},
    },
    "ML-IMPACT": {
        "normal": set(),
        "suspicious": {"impact_or_tamper", "defense_evasion_or_tamper", "file_integrity_tamper"},
    },
}

ML_LABEL_BEHAVIOR_PLAN_ALIASES = {
    "ssh_invalid_user_enumeration": ("ML-AUTH", "auth_attack_or_abuse", "suspicious", "behavior_alias:ssh_invalid_user_enumeration"),
    "auth_attack_or_abuse": ("ML-AUTH", "auth_attack_or_abuse", "attack", "behavior_alias:auth_attack_or_abuse"),
    "brute_force_or_auth_attack": ("ML-AUTH", "auth_attack_or_abuse", "attack", "behavior_alias:brute_force_or_auth_attack"),
    "ssh_login_normal": ("ML-AUTH", "ssh_login_normal", "benign", "behavior_alias:ssh_login_normal"),
    "expected_auth_activity": ("ML-AUTH", "expected_auth_activity", "benign", "behavior_alias:expected_auth_activity"),
    "sudo_root_access": ("ML-SUDO", "sudo_escalation_or_root_access", "attack", "behavior_alias:sudo_root_access"),
    "sudo_escalation_or_root_access": ("ML-SUDO", "sudo_escalation_or_root_access", "attack", "behavior_alias:sudo_escalation_or_root_access"),
    "sudo_normal": ("ML-SUDO", "sudo_normal", "benign", "behavior_alias:sudo_normal"),
    "suspicious_process": ("ML-PROC", "suspicious_process", "suspicious", "behavior_alias:suspicious_process"),
    "lolbin_abuse": ("ML-PROC", "lolbin_abuse", "suspicious", "behavior_alias:lolbin_abuse"),
    "rare_process": ("ML-PROC", "suspicious_process", "suspicious", "behavior_alias:rare_process"),
    "process_normal": ("ML-PROC", "process_normal", "benign", "behavior_alias:process_normal"),
    "routine_exec": ("ML-PROC", "routine_exec", "benign", "behavior_alias:routine_exec"),
    "persistence_service_mod": ("ML-SERVICE", "persistence_service_mod", "suspicious", "behavior_alias:persistence_service_mod"),
    "service_normal": ("ML-SERVICE", "service_normal", "benign", "behavior_alias:service_normal"),
    "normal_network": ("ML-NET", "normal_network", "benign", "behavior_alias:normal_network"),
    "expected_outbound": ("ML-NET", "expected_outbound", "benign", "behavior_alias:expected_outbound"),
    "network_abuse": ("ML-NET", "network_abuse", "suspicious", "behavior_alias:network_abuse"),
    "clean_sequence_normal": ("ML-SEQ", "clean_sequence_normal", "benign", "behavior_alias:clean_sequence_normal"),
    "suspicious_sequence": ("ML-SEQ", "suspicious_sequence", "suspicious", "behavior_alias:suspicious_sequence"),
    "user_behavior_normal": ("ML-USER", "user_behavior_normal", "benign", "behavior_alias:user_behavior_normal"),
    "user_behavior_anomaly": ("ML-USER", "user_behavior_anomaly", "suspicious", "behavior_alias:user_behavior_anomaly"),
    "host_behavior_normal": ("ML-HOST", "host_behavior_normal", "benign", "behavior_alias:host_behavior_normal"),
    "host_behavior_anomaly": ("ML-HOST", "host_behavior_anomaly", "suspicious", "behavior_alias:host_behavior_anomaly"),
    "first_seen_behavior": ("ML-HOST", "host_behavior_anomaly", "suspicious", "behavior_alias:first_seen_behavior"),
    "db_login_normal": ("ML-DBAUTH", "db_login_normal", "benign", "behavior_alias:db_login_normal"),
    "expected_db_activity": ("ML-DBAUTH", "expected_db_activity", "benign", "behavior_alias:expected_db_activity"),
    "db_login_abuse": ("ML-DBAUTH", "db_login_abuse", "attack", "behavior_alias:db_login_abuse"),
    "dns_normal": ("ML-DNS", "dns_normal", "benign", "behavior_alias:dns_normal"),
    "dns_anomaly": ("ML-DNS", "dns_anomaly", "suspicious", "behavior_alias:dns_anomaly"),
    "web_request_normal_linked": ("ML-WEBPOST", "web_request_normal_linked", "benign", "behavior_alias:web_request_normal_linked"),
    "web_attack_or_post_exploit": ("ML-WEBPOST", "web_attack_or_post_exploit", "attack", "behavior_alias:web_attack_or_post_exploit"),
    "cleanup_normal": ("ML-IMPACT", "cleanup_normal", "benign", "behavior_alias:cleanup_normal"),
    "impact_or_tamper": ("ML-IMPACT", "impact_or_tamper", "attack", "behavior_alias:impact_or_tamper"),
}

ML_CONFIG_DEFAULT_STATUS = {
    "ML-AUTH": "readiness_blocked",
    "ML-SUDO": "readiness_blocked",
    "ML-PROC": "readiness_blocked",
    "ML-SERVICE": "readiness_blocked",
    "ML-NET": "readiness_blocked",
    "ML-SEQ": "readiness_blocked",
    "ML-USER": "readiness_blocked",
    "ML-HOST": "readiness_blocked",
    "ML-DBAUTH": "readiness_blocked",
    "ML-DNS": "readiness_blocked",
    "ML-WEBPOST": "readiness_blocked",
    "ML-IMPACT": "readiness_blocked",
}

ML_FAMILY_READINESS = {
    "ML-AUTH": {
        "where": "LOWER(COALESCE(category, )) = auth",
        "required_events": 2000,
        "required_normal_labels": 100,
        "required_suspicious_labels": 50,
        "phase_gate": int(Phase.PHASE_2),
        "field_requirements": {"host_fill_rate": 0.50, "user_fill_rate": 0.50, "src_ip_fill_rate": 0.50},
        "hard_field_rates": {"host_fill_rate", "user_fill_rate", "src_ip_fill_rate"},
        "normal_behaviors": {"expected_auth_activity", "ssh_login_normal", "session_open_normal"},
        "suspicious_behaviors": {
            "root_ssh_login", "ssh_auth_failure", "ssh_invalid_user_enumeration",
            "account_lockout_after_auth_failures", "openvpn_auth_failure",
            "sssd_auth_failure", "winbind_auth_failure", "winbind_account_lockout",
            "strongswan_auth_failure", "wireguard_handshake_failure", "smtp_auth_failure",
        },
    },
    "ML-SUDO": {
        "where": "LOWER(COALESCE(action, )) IN (sudo, sudo_fail, su, su_fail)",
        "required_events": 500,
        "required_normal_labels": 100,
        "required_suspicious_labels": 50,
        "phase_gate": int(Phase.PHASE_2),
        "field_requirements": {"host_fill_rate": 0.50, "user_fill_rate": 0.50, "process_fill_rate": 0.30},
        "hard_field_rates": {"host_fill_rate", "user_fill_rate"},
        "normal_behaviors": {"sudo_normal", "expected_sudo_activity"},
        "suspicious_behaviors": {
            "sudo_root_access", "su_root_access", "sudo_auth_failure", "dangerous_sudo_execution",
        },
    },
    "ML-PROC": {
        "where": "LOWER(COALESCE(category, )) = process",
        "required_events": 10000,
        "required_normal_labels": 300,
        "required_suspicious_labels": 150,
        "phase_gate": int(Phase.PHASE_1),
        "field_requirements": {"process_fill_rate": 0.30, "host_fill_rate": 0.05},
        "hard_field_rates": set(),
        "normal_behaviors": {
            "process_normal", "routine_process_activity", "routine_system_event",
            "benign_activity", "routine_file_access",
        },
        "suspicious_behaviors": {
            "service_shell_spawn", "reverse_shell_execution", "temp_interpreter_execution",
            "base64_obfuscated_execution", "ptrace_process_injection",
            "named_pipe_shell_communication", "backdoor_port_listener",
            "unusual_suid_execution", "credential_material_access",
            "outbound_exfiltration_activity", "container_abuse_activity",
            "ssh_tunnel_command_and_control", "payload_download_activity",
            "destructive_impact_activity", "rare_process", "process_discovery",
            "account_discovery", "lolbin_execution", "lolbin_abuse",
        },
    },
    "ML-SERVICE": {
        "where": "LOWER(COALESCE(category, )) IN (system, service)",
        "required_events": 1000,
        "required_normal_labels": 100,
        "required_suspicious_labels": 50,
        "phase_gate": int(Phase.PHASE_2),
        "field_requirements": {"host_fill_rate": 0.50, "process_fill_rate": 0.30},
        "hard_field_rates": {"host_fill_rate"},
        "normal_behaviors": {"service_normal", "system_service_normal", "routine_system_event"},
        "suspicious_behaviors": {
            "persistence_service_mod", "service_modification", "service_shell_spawn",
            "service_disable", "service_stop_abuse",
        },
    },
    "ML-NET": {
        "where": "LOWER(COALESCE(category, )) = network",
        "required_events": 5000,
        "required_normal_labels": 200,
        "required_suspicious_labels": 100,
        "phase_gate": int(Phase.PHASE_1),
        "field_requirements": {"src_ip_fill_rate": 0.50, "dst_ip_fill_rate": 0.30, "dst_port_fill_rate": 0.30},
        "hard_field_rates": {"src_ip_fill_rate"},
        "normal_behaviors": {"normal_network", "expected_network_activity", "benign_activity"},
        "suspicious_behaviors": {
            "outbound_exfiltration_activity", "ssh_tunnel_command_and_control",
            "dns_beacon_like", "network_scan", "outbound_c2", "firewall_scan",
        },
    },
    "ML-SEQ": {
        "where": "LOWER(COALESCE(category, )) IN (auth, process, network, system, db)",
        "required_events": 1000,
        "required_normal_labels": 150,
        "required_suspicious_labels": 100,
        "phase_gate": int(Phase.PHASE_3),
        "field_requirements": {"host_fill_rate": 0.50, "user_fill_rate": 0.50},
        "hard_field_rates": {"host_fill_rate", "user_fill_rate"},
        "normal_behaviors": {"clean_sequence_normal"},
        "suspicious_behaviors": {"lateral_movement", "web_post_exploitation", "suspicious_sequence"},
        "require_process_tree": True,
    },
    "ML-USER": {
        "where": "NULLIF(BTRIM(COALESCE(username, )), ) IS NOT NULL",
        "required_events": 1000,
        "required_normal_labels": 200,
        "required_suspicious_labels": 80,
        "phase_gate": int(Phase.PHASE_2),
        "field_requirements": {"user_fill_rate": 0.80, "host_fill_rate": 0.50, "src_ip_fill_rate": 0.50},
        "hard_field_rates": {"user_fill_rate", "host_fill_rate"},
        "normal_behaviors": {"user_behavior_normal", "expected_auth_activity"},
        "suspicious_behaviors": {"account_discovery", "rare_user_behavior", "user_behavior_anomaly"},
    },
    "ML-HOST": {
        "where": "NULLIF(BTRIM(COALESCE(host, )), ) IS NOT NULL",
        "required_events": 5000,
        "required_normal_labels": 300,
        "required_suspicious_labels": 100,
        "phase_gate": int(Phase.PHASE_2),
        "field_requirements": {"host_fill_rate": 0.80, "process_fill_rate": 0.30},
        "hard_field_rates": {"host_fill_rate"},
        "normal_behaviors": {"host_behavior_normal", "routine_system_event"},
        "suspicious_behaviors": {"host_behavior_anomaly", "destructive_impact_activity", "persistence_service_mod"},
    },
    "ML-DBAUTH": {
        "where": "LOWER(COALESCE(category, )) = db",
        "required_events": 300,
        "required_normal_labels": 80,
        "required_suspicious_labels": 40,
        "phase_gate": int(Phase.PHASE_2),
        "field_requirements": {"user_fill_rate": 0.50, "host_fill_rate": 0.30},
        "hard_field_rates": {"user_fill_rate"},
        "normal_behaviors": {"expected_db_activity", "db_login_normal"},
        "suspicious_behaviors": {"db_auth_failure", "db_login_abuse"},
    },
    "ML-DNS": {
        "where": "LOWER(COALESCE(source, )) IN (dns, named, bind, dnsmasq, systemd-resolved, resolved) OR LEFT(LOWER(COALESCE(action, )), 3) = dns",
        "required_events": 3000,
        "required_normal_labels": 150,
        "required_suspicious_labels": 60,
        "phase_gate": int(Phase.PHASE_2),
        "field_requirements": {"src_ip_fill_rate": 0.30, "dst_ip_fill_rate": 0.30},
        "hard_field_rates": set(),
        "normal_behaviors": {"dns_normal", "normal_dns"},
        "suspicious_behaviors": {"dns_beacon_like", "dns_anomaly"},
    },
    "ML-WEBPOST": {
        "where": "LOWER(COALESCE(category, )) = web_attack",
        "required_events": 2000,
        "required_normal_labels": 150,
        "required_suspicious_labels": 80,
        "phase_gate": int(Phase.PHASE_3),
        "field_requirements": {"host_fill_rate": 0.30, "process_fill_rate": 0.30},
        "hard_field_rates": set(),
        "normal_behaviors": {"web_request_normal_linked"},
        "suspicious_behaviors": {
            "web_shell_upload", "sql_injection_attempt", "path_traversal_attempt",
            "xss_attempt", "xxe_attempt", "dvwa_exploitation_attempt", "web_post_exploitation",
        },
        "linked_process_where": "LOWER(COALESCE(category, )) = process",
        "linked_process_required_events": 500,
    },
    "ML-IMPACT": {
        "where": "LOWER(COALESCE(category, )) IN (process, filesystem) AND LOWER(COALESCE(risk_bucket, )) IN (suspicious, malicious)",
        "required_events": 500,
        "required_normal_labels": 80,
        "required_suspicious_labels": 60,
        "phase_gate": int(Phase.PHASE_3),
        "field_requirements": {"process_fill_rate": 0.30, "host_fill_rate": 0.30},
        "hard_field_rates": set(),
        "normal_behaviors": {"cleanup_normal", "routine_system_event"},
        "suspicious_behaviors": {"destructive_impact_activity", "log_tampering", "impact", "destructive_behavior"},
    },
}

ML_SCHEMA_CONTRACT = {
    "labels_existing": (
        "source_trust", "model_usage_scope", "event_class", "behavior_label",
        "learnable", "label_reason", "evidence_fields",
        "bootstrap_job_id", "label_batch_id", "correlation_id",
    ),
    "labels_future": (
        "ml_family", "ml_label", "label_family", "field_quality_summary",
        "time_context", "family_gate_snapshot",
    ),
    "alerts_future": (
        "ml_family", "ml_label", "ml_family_status", "readiness_reason",
        "field_quality_summary", "time_context", "explainability_json",
        "no_action_contract", "family_gate_snapshot",
    ),
}

__all__ = [
    "ML_FAMILY_BEHAVIOR_ALIASES",
    "ML_LABEL_BEHAVIOR_PLAN_ALIASES",
    "ML_CONFIG_DEFAULT_STATUS",
    "ML_FAMILY_READINESS",
    "ML_SCHEMA_CONTRACT",
]
