from __future__ import annotations

from typing import Any, Mapping


SUPPORTED_LANGUAGES = ("en", "tr")

_LANGUAGE_ALIASES = {
    "en": "en",
    "eng": "en",
    "english": "en",
    "en_us": "en",
    "en_gb": "en",
    "tr": "tr",
    "turkish": "tr",
    "turkce": "tr",
    "turkçe": "tr",
    "türkçe": "tr",
    "tr_tr": "tr",
}

_EXPLANATION_CATALOG = {
    "tr": {
        "deterministic_explanation_title": "Deterministik Alert Açıklaması",
        "alert_id": "Alert ID",
        "rule_id": "Rule ID",
        "severity": "Severity",
        "risk_score": "Risk Skoru",
        "entity": "Entity",
        "message": "Mesaj",
        "ml_alert": "ML alert",
        "ml_family": "ML Family",
        "ml_label": "ML Label",
        "ml_score_confidence": "ML Score / Confidence",
        "unknown": "bilinmiyor",
        "unspecified": "belirtilmemiş",
        "message_missing": "Mesaj bilgisi yok.",
        "why_seen_abnormal": "Neden anormal görüldü?",
        "why_seen_abnormal_fallback": "Deterministik açıklama üretildi.",
        "why_triggered": "Neden tetiklendi?",
        "why_triggered_fallback": "Mevcut rule alanlarından fallback açıklama üretildi.",
        "top_features": "Top features",
        "time_context": "Time context",
        "baseline_deviation": "Baseline deviation",
        "important_event_fields": "Önemli event/log alanları",
        "key_evidence": "Kanıt özetleri",
        "review_checks": "Kullanıcı neyi kontrol etmeli?",
        "metadata_missing_ml": "Not: detay metadata eksik; mevcut ML alert alanlarından fallback açıklama üretildi.",
        "metadata_missing_rule": "Not: detay metadata yok; açıklama mevcut rule/message/severity/risk/entity alanlarından üretildi.",
        "summary_heading": "Kısa Özet",
        "technical_heading": "Teknik Anlam",
        "risk_heading": "Risk Değerlendirmesi",
        "evidence_heading": "Kanıtlar",
        "scenario_heading": "Olası Saldırı Senaryosu",
        "false_positive_heading": "False Positive Kontrolü",
        "mitigation_heading": "Önlem / Mitigation",
        "review_steps_heading": "Sonraki İnceleme Adımları",
        "related_event_summary": "İlişkili olay özeti",
        "related_alert_count": "ilişkili alarm sayısı",
        "same_ip_user_rule": "Aynı IP/kullanıcı/kural ilişkisi",
        "same_ip": "aynı IP",
        "same_entity": "aynı varlık/kullanıcı",
        "same_rule": "aynı kural",
        "same_ip_alert_count": "Aynı IP alarm sayısı",
        "same_rule_alert_count": "Aynı kural alarm sayısı",
        "time_range": "Zaman aralığı",
        "first_seen": "ilk görülme",
        "last_seen": "son görülme",
        "none": "yok",
        "high_critical_related": "High/Critical ilişkili alarm sayısı",
        "count": "adet",
        "top_related_rules": "öne çıkan ilişkili kurallar",
        "source_type": "Kaynak tipi",
        "source_ip": "Kaynak IP",
        "asset": "Varlık/Kullanıcı",
        "rule_prefix": "Kural",
        "importance": "Önem",
        "llm_disabled_note": "LLM devre dışı, deterministik açıklama gösteriliyor.",
        "llm_unavailable_note": "LLM sağlayıcısı geçici olarak yanıt vermedi; deterministik açıklama gösteriliyor.",
        "reason": "Neden",
        "deterministic_read_failed": "Deterministik açıklama okunamadı: {error}",
        "rule_trigger_sudo": "{user} için sudo/root yetki davranışı kural eşiğini aştı.",
        "rule_trigger_dns": "DNS davranışı beklenen profilden saptığı için kural tetiklendi.",
        "rule_trigger_web": "Web isteği kalıbı bilinen saldırı/pivot davranışıyla eşleşti.",
        "rule_trigger_auth": "Kimlik doğrulama davranışı saldırı veya kötüye kullanım kalıbıyla eşleşti.",
        "rule_trigger_process": "{process} etrafındaki olay deseni tanımlı güvenlik kuralıyla eşleşti.",
        "rule_trigger_default": "Olay alanları tanımlı güvenlik kuralı koşullarını karşıladığı için alarm oluştu.",
        "review_step_context": "İlgili host, kullanıcı ve süreç bağlamını doğrula.",
        "review_step_pattern": "Aynı rule_id için son olayları ve tekrar eden örüntüyü incele.",
        "review_step_isolation": "Gerekirse etkilenen varlıkta geçici izolasyon veya ek log toplama başlat.",
        "review_step_web": "İlgili web erişim kayıtlarını ve kaynak IP davranışını karşılaştır.",
        "ml_trigger_sudo": "Bu kullanıcı bu bağlamda olağandışı sudo/root davranışı gösteriyor.",
        "ml_trigger_proc": "Bu process bu hostta beklenen davranış profilinden sapıyor.",
        "ml_trigger_net": "Bu dış bağlantı normal ağ profilinden sapıyor.",
        "ml_trigger_baseline": "Olay, family baseline beklentilerinden anlamlı biçimde ayrışıyor.",
        "ml_trigger_time": "Olay alışılmadık saat bağlamında gözlendiği için ML destek skoru yükseldi.",
        "ml_trigger_features": "ML destek skoru; alan doluluğu, family eşleşmesi ve zaman bağlamı birleşimiyle yükseldi.",
        "ml_trigger_default": "ML destek skoru helper'ı olayın family bağlamında anomali sinyali gördü.",
        "ml_review_fields": "İlgili olay alanlarını ve top_features özetini doğrula.",
        "ml_review_compare": "Aynı family için son ML destek skoru örnekleriyle karşılaştır.",
        "ml_review_proc": "Sürecin bu host ve kullanıcı için beklenen yürütme profiline uyup uymadığını kontrol et.",
        "ml_review_net": "Kaynak/hedef ağ davranışını son normal akışlarla karşılaştır.",
        "ui_summary_template": "{severity} seviyesinde {rule_id} alarmı {actor} için üretildi. Bu kayıt {source} kaynağında gözlenen davranışın tehdit veya kötüye kullanım belirtisi olabileceğini gösterir.",
        "ui_fallback_why": "Mevcut alert metadata alanlarından deterministic özet üretildi.",
        "ui_risk_template": "Risk skoru {risk_score}. Alarmın seviyesi {severity} olarak işaretlenmiş. Bu yüzden olay yanlış yapılandırma kadar masum bir sebepten de kaynaklanabilir, gerçek bir brute force, yetkisiz erişim denemesi veya kuralın kapsadığı başka bir saldırı davranışı da olabilir.",
        "ui_review_step_1": "Ham event, parsed metadata ve alert mesajını yan yana inceleyip alarmın gerçekten aynı olaya ait olduğundan emin ol.",
        "ui_review_step_2": "Aynı entity, kullanıcı veya source IP için yakın zamanlı diğer alarmları ve logları korele et.",
        "ui_review_step_3": "Kuralın beklediği davranış ile sistemdeki meşru operasyon arasında tutarlılık olup olmadığını doğrula.",
        "ui_false_positive": "Yanlış pozitif ihtimali vardır. Özellikle bakım çalışması, hatalı parola denemeleri, otomasyon araçları veya güvenlik tarayıcıları benzer izi bırakabilir. Kaynak IP, kullanıcı, süreç adı ve zaman aralığı ham loglarla doğrulanmadan kesin hüküm verilmemelidir.",
        "ui_scenario": "Olası senaryo; saldırganın kimlik doğrulama, yetki yükseltme, web isteği, süreç zinciri veya aynı kuralla ilişkili başka bir davranış üzerinden sistemi istismar etmeye çalışmasıdır. Alarm tek başına kesin ihlal kanıtı olmayabilir; ancak ilişkili kayıtlarla birlikte değerlendirilmelidir.",
        "ui_mitigation_1": "Etkilenen kullanıcı, host veya IP için ilgili log penceresinde ek doğrulama yap.",
        "ui_mitigation_2": "Gerekirse oturum, erişim anahtarı veya riskli hesabı geçici olarak sınırla.",
        "ui_mitigation_3": "Kaynak IP veya istemci davranışı düşmanca görünüyorsa mevcut manuel block/guard akışını değerlendir.",
        "ui_mitigation_4": "Kuralın kapsadığı servis için parola politikası, MFA, rate limit veya erişim kontrolü gibi önlemleri gözden geçir.",
        "ui_related_step_1": "Aynı kaynak IP için {same_source_ip_count} ve aynı kural için {same_rule_count} alarmı zaman çizelgesiyle doğrula.",
        "ui_related_step_2": "İlk görülme {first_seen} ve son görülme {last_seen} aralığını ham loglarla karşılaştır.",
        "llm_empty_response": "LLM sağlayıcısı boş yanıt döndürdü.",
        "llm_too_short": "LLM sağlayıcısı çok kısa yanıt döndürdü.",
        "llm_low_quality": "LLM sağlayıcısı eksik veya düşük kaliteli yanıt döndürdü.",
        "llm_disabled": "LLM devre dışı (enabled: false).",
        "llm_missing_api_key": "LLM devre dışı: eksik API anahtarı ({env}).",
        "llm_not_enabled": "LLM açıklaması üretilemedi: Gemini istemcisi etkin değil.",
        "llm_empty_gemini": "LLM açıklaması üretilemedi: Gemini boş yanıt döndürdü.",
        "llm_generic_error_prefix": "LLM açıklaması üretilemedi",
        "llm_note": "LLM Notu",
    },
    "en": {
        "deterministic_explanation_title": "Deterministic Alert Explanation",
        "alert_id": "Alert ID",
        "rule_id": "Rule ID",
        "severity": "Severity",
        "risk_score": "Risk Score",
        "entity": "Entity",
        "message": "Message",
        "ml_alert": "ML alert",
        "ml_family": "ML Family",
        "ml_label": "ML Label",
        "ml_score_confidence": "ML Score / Confidence",
        "unknown": "unknown",
        "unspecified": "unspecified",
        "message_missing": "No message information available.",
        "why_seen_abnormal": "Why was it considered anomalous?",
        "why_seen_abnormal_fallback": "A deterministic explanation was generated.",
        "why_triggered": "Why was it triggered?",
        "why_triggered_fallback": "A fallback explanation was generated from the current rule fields.",
        "top_features": "Top features",
        "time_context": "Time context",
        "baseline_deviation": "Baseline deviation",
        "important_event_fields": "Important event/log fields",
        "key_evidence": "Key evidence",
        "review_checks": "What should the operator review?",
        "metadata_missing_ml": "Note: detailed metadata was missing; a fallback explanation was generated from the current ML alert fields.",
        "metadata_missing_rule": "Note: detailed metadata was missing; the explanation was generated from the current rule, message, severity, risk, and entity fields.",
        "summary_heading": "Short Summary",
        "technical_heading": "Technical Meaning",
        "risk_heading": "Risk Assessment",
        "evidence_heading": "Evidence",
        "scenario_heading": "Possible Attack Scenario",
        "false_positive_heading": "False Positive Check",
        "mitigation_heading": "Mitigation",
        "review_steps_heading": "Next Investigation Steps",
        "related_event_summary": "Related event summary",
        "related_alert_count": "related alert count",
        "same_ip_user_rule": "Same IP/entity/rule relationship",
        "same_ip": "same IP",
        "same_entity": "same entity/user",
        "same_rule": "same rule",
        "same_ip_alert_count": "Same IP alert count",
        "same_rule_alert_count": "Same rule alert count",
        "time_range": "Time range",
        "first_seen": "first seen",
        "last_seen": "last seen",
        "none": "none",
        "high_critical_related": "High/Critical related alert count",
        "count": "count",
        "top_related_rules": "top related rules",
        "source_type": "Source type",
        "source_ip": "Source IP",
        "asset": "Asset/User",
        "rule_prefix": "Rule",
        "importance": "Severity",
        "llm_disabled_note": "LLM is disabled, showing the deterministic explanation.",
        "llm_unavailable_note": "The LLM provider did not respond successfully; showing the deterministic explanation.",
        "reason": "Reason",
        "deterministic_read_failed": "Could not load deterministic explanation: {error}",
        "rule_trigger_sudo": "Sudo/root privilege behavior for {user} exceeded the rule threshold.",
        "rule_trigger_dns": "The DNS behavior deviated from the expected profile, so the rule was triggered.",
        "rule_trigger_web": "The web request pattern matched a known attack or pivot behavior.",
        "rule_trigger_auth": "The authentication behavior matched an attack or abuse pattern.",
        "rule_trigger_process": "The event pattern around {process} matched a defined security rule.",
        "rule_trigger_default": "The alert was generated because the event fields satisfied the defined security rule conditions.",
        "review_step_context": "Validate the related host, user, and process context.",
        "review_step_pattern": "Review recent events and any repeated pattern for the same rule_id.",
        "review_step_isolation": "If needed, start temporary isolation or collect additional logs from the affected asset.",
        "review_step_web": "Compare the related web access records and source IP behavior.",
        "ml_trigger_sudo": "This user shows unusual sudo/root behavior in this context.",
        "ml_trigger_proc": "This process deviates from the expected behavior profile on this host.",
        "ml_trigger_net": "This outbound connection deviates from the normal network profile.",
        "ml_trigger_baseline": "The event meaningfully deviates from the family baseline expectations.",
        "ml_trigger_time": "The ML support score increased because the event was observed in an unusual time context.",
        "ml_trigger_features": "The ML support score increased due to a combination of field completeness, family alignment, and time context.",
        "ml_trigger_default": "The ML support-score helper observed an anomaly signal in the event's family context.",
        "ml_review_fields": "Validate the relevant event fields and the top_features summary.",
        "ml_review_compare": "Compare the event against recent ML support-score examples from the same family.",
        "ml_review_proc": "Check whether the process matches the expected execution profile for this host and user.",
        "ml_review_net": "Compare the source and destination network behavior with recent normal traffic.",
        "ui_summary_template": "A {severity} severity {rule_id} alert was generated for {actor}. This record suggests that the behavior observed in the {source} source may indicate threat activity or abuse.",
        "ui_fallback_why": "A deterministic summary was generated from the current alert metadata fields.",
        "ui_risk_template": "The risk score is {risk_score}. The alert severity is marked as {severity}. This means the event may still be caused by misconfiguration or benign activity, but it could also reflect a real brute-force attempt, unauthorized access attempt, or another attack behavior covered by the rule.",
        "ui_review_step_1": "Review the raw event, parsed metadata, and alert message side by side to confirm they refer to the same activity.",
        "ui_review_step_2": "Correlate nearby alerts and logs for the same entity, user, or source IP.",
        "ui_review_step_3": "Verify whether the expected behavior of the rule is consistent with legitimate operations on the system.",
        "ui_false_positive": "A false positive is possible. Maintenance activity, incorrect password attempts, automation tools, or security scanners can leave a similar trace. Do not make a final judgment before validating the source IP, user, process name, and time window against the raw logs.",
        "ui_scenario": "A possible scenario is that an attacker is attempting to abuse the system through authentication, privilege escalation, web requests, process chaining, or another behavior related to the same rule. The alert alone may not be conclusive proof of compromise, but it should be evaluated with related records.",
        "ui_mitigation_1": "Perform additional validation for the affected user, host, or IP within the relevant log window.",
        "ui_mitigation_2": "If necessary, temporarily restrict the session, access key, or risky account.",
        "ui_mitigation_3": "If the source IP or client behavior appears hostile, evaluate the existing manual block/guard workflow.",
        "ui_mitigation_4": "Review controls such as password policy, MFA, rate limiting, or access control for the affected service.",
        "ui_related_step_1": "Validate the timeline for {same_source_ip_count} alerts from the same source IP and {same_rule_count} alerts for the same rule.",
        "ui_related_step_2": "Compare the raw logs against the first seen time {first_seen} and the last seen time {last_seen}.",
        "llm_empty_response": "The LLM provider returned an empty response.",
        "llm_too_short": "The LLM provider returned a response that was too short.",
        "llm_low_quality": "The LLM provider returned an incomplete or low-quality response.",
        "llm_disabled": "LLM is disabled (enabled: false).",
        "llm_missing_api_key": "LLM is disabled: missing API key ({env}).",
        "llm_not_enabled": "LLM explanation could not be generated: Gemini client is not active.",
        "llm_empty_gemini": "LLM explanation could not be generated: Gemini returned an empty response.",
        "llm_generic_error_prefix": "LLM explanation could not be generated",
        "llm_note": "LLM Note",
    },
}

_SYSTEM_CATALOG = {
    "tr": {
        "last_n_days": "Son {days} gün",
        "last_7_days": "Son 7 gün",
        "unknown": "bilinmiyor",
        "unspecified": "belirtilmemiş",
        "rule_validation_report": "Kural Doğrulama Raporu",
        "loaded_rules": "Yüklenen kural",
        "all_rules_valid": "Tüm kurallar geçerli",
        "error_count": "Hata sayısı",
        "smoke_test": "Smoke Test",
        "distro": "Distro",
        "unsupported_distro": "Desteklenmeyen distro",
        "distro_supported": "Distro destekleniyor",
        "db_health_failed": "DB health başarısız",
        "postgres_connection_ok": "PostgreSQL bağlantısı başarılı",
        "normalize_failed": "Normalize başarısız",
        "normalize_ok": "Normalize başarılı",
        "detection_pipeline_ok": "Detection pipeline çalıştı",
        "startup": "Başlatılıyor",
        "report_title": "SIEM Raporu",
        "db": "DB",
        "db_url_missing": "PostgreSQL URL yok — başlatma başarısız olacak",
        "db_url_hint_env": "DATABASE_URL=postgresql://user:pass@host:5432/db",
        "db_url_hint_config": "veya config.yml: database.url",
        "preflight_config_loaded": "Config dosyası okundu.",
        "preflight_config_missing": "Config dosyası bulunamadı; varsayılan/boş config ile devam ediliyor.",
        "preflight_config_suggestion": "config/config.yml varlığını ve izinlerini doğrulayın.",
        "preflight_distro_supported": "Desteklenen dağıtım ailesi algılandı.",
        "preflight_distro_unsupported": "Desteklenmeyen veya EOL dağıtım algılandı.",
        "preflight_distro_suggestion": "Desteklenen ailelerden birine geçin veya yalnız read-only inceleme ile devam edin.",
        "preflight_database_missing": "DATABASE_URL veya database.url tanımlı değil.",
        "preflight_database_healthy": "PostgreSQL bağlantısı ve şema sağlıklı.",
        "preflight_database_degraded": "PostgreSQL health check degraded döndü.",
        "preflight_database_unreadable": "PostgreSQL health okunamadı.",
        "preflight_database_suggestion": "DATABASE_URL, PostgreSQL erişimi ve schema health durumunu doğrulayın.",
        "preflight_sources_healthy": "Tüm aktif kaynaklar erişilebilir.",
        "preflight_sources_degraded": "Bazı log kaynakları kapalı veya eksik.",
        "preflight_sources_unreadable": "Kaynak sağlık özeti okunamadı.",
        "preflight_sources_suggestion": "Eksik log path veya journald erişimini doğrulayın.",
        "preflight_ml_safety_ok": "ML active layer audit_only/no-action contract ile güvenli modda.",
        "preflight_ml_safety_degraded": "ML güvenlik kontratı beklenen read-only/audit-only varsayılanlardan sapıyor.",
        "preflight_ml_suggestion": "active_decision_layer.enabled=false, mode=audit_only ve no_action_contract=true kalmalı.",
        "preflight_ip_blocking_manual_only": "IP blocking automatic disabled; yalnız manual operator akışı desteklenir.",
        "preflight_ip_suggestion": "Gerçek block/unblock yalnız explicit manual operator akışıyla kullanılmalı.",
        "preflight_locks_ok": "Read-only güvenlik kilitleri aktif.",
        "preflight_locks_degraded": "Bazı güvenlik kilitleri beklenen durumda değil.",
        "preflight_locks_suggestion": "UI sadece read-only modda kullanılmalı; runtime güvenlik kontratlarını doğrulayın.",
        "preflight_startup_error": "Preflight sırasında beklenmeyen bir hata oluştu.",
        "preflight_startup_suggestion": "Config yolu, Python environment ve temel backend importlarını doğrulayın.",
        "historical_preview_manual_only_message": "Geçmiş log taraması yalnız kullanıcı scan butonuna bastığında çalışır.",
        "ml_mode_disabled": "Disabled",
        "ml_mode_audit_only": "Audit-only",
        "ml_mode_shadow": "Shadow",
        "ml_mode_unknown": "Unknown",
        "ml_safety_no_autonomous_action": "Otonom aksiyon yok",
        "ml_training_not_run": "Henüz hiçbir model eğitilmedi.",
        "ml_training_waiting_for_labels": "Yeterli yüksek kaliteli etiketli veri bekleniyor.",
        "ml_training_status_available": "Training meta verisi mevcut.",
        "ml_historical_scan_not_run": "Geçmiş log taraması henüz çalıştırılmadı. Gerektiğinde CLI üzerinden çalıştırın.",
        "ml_historical_scan_cli_only": "CLI/manual only",
        "never": "Henüz yok",
        "not_available": "mevcut değil",
        "llm": "LLM",
        "active": "Aktif",
        "disabled_config": "Devre dışı  (config: llm.enabled: false)",
        "enable_hint": "Aktifleştirmek için: llm.enabled: true",
        "missing_api_key": "api_key eksik",
        "mock_backend": "Mock backend  (gerçek API çağrısı yok — test modu)",
        "status_unknown": "durum bilinmiyor",
        "threat_intel": "Threat Intel",
        "otx": "OTX",
        "disabled_threat_intel": "Devre dışı  (threat_intel.enabled: false)",
        "free_feeds_otx_active": "{count} ücretsiz feed + OTX aktif",
        "otx_key_missing": "Key yok  ({count} ücretsiz feed aktif)",
        "otx_hint": "AlienVault OTX için: config.yml: threat_intel.otx_api_key  veya  env: OTX_API_KEY",
        "free_feeds_active": "{count} ücretsiz feed aktif",
        "distro_label": "Distro",
        "family_label": "aile",
        "unsupported": "Desteklenmiyor",
        "detect_error": "Tespit hatası",
        "log_sources": "Log Kaynakları",
        "single_source": "tek kaynak",
        "active_count": "aktif",
        "none_enabled_test_mode": "Hiçbiri etkin  → test moduna geçilecek",
        "path_not_defined": "path tanımlı değil — kaynak başlamayacak",
        "file_missing": "dosya yok",
        "source_disabled_quietly": "kaynak sessizce devre dışı kalacak",
        "phase": "Faz",
        "days": "gün",
        "hours": "saat",
        "generated_at": "Oluşturuldu",
        "since": "Başlangıç",
        "total_alerts": "Toplam Alert",
        "incident": "Incident",
        "severity_distribution": "Severity Dağılımı",
        "severity": "Önem",
        "count": "Sayı",
        "distribution": "Dağılım",
        "hourly_distribution": "Saatlik Dağılım",
        "ip_reputation": "IP Reputation / AbuseIPDB",
        "reports": "Reports",
        "country": "Country",
        "suggestion_status": "Suggestion Status",
        "no_reputation": "No reputation enrichment available.",
        "alert_explanations": "Alert Açıklamaları",
        "no_alerts_to_explain": "Açıklanacak alert bulunamadı.",
        "explanation_intro_recent": "Son {limit} alert için kısa deterministic özet gösterilir.",
        "explanation_intro_fallback": "Rapor zaman aralığında alert yoksa, aşağıda son mevcut alert açıklamaları gösterilir.",
        "top_triggered_rules": "En Çok Tetiklenen Kurallar",
        "rule": "Kural",
        "recent_incidents": "Son Incident'ler",
        "time": "Zaman",
        "title": "Başlık",
        "risk_score": "Risk Skoru",
        "entity": "Entity",
        "status": "Durum",
        "no_incidents_yet": "Henüz incident yok.",
        "most_active_entities": "En Aktif Entity'ler",
        "ip_or_user": "IP / Kullanıcı",
        "most_active_users": "En Aktif Kullanıcılar",
        "user": "Kullanıcı",
        "why_triggered": "Neden tetiklendi?",
        "control_recommendations": "Kontrol önerileri",
        "important_evidence_fields": "Önemli kanıt alanları",
        "key_evidence": "Kanıt özetleri",
        "metadata_missing_short": "Metadata eksikti; kısa fallback açıklama gösteriliyor.",
        "no_important_fields": "Önemli event/log alanı bulunamadı.",
        "manual_validate_context": "İlgili host, kullanıcı ve süreç bağlamını manuel olarak doğrula.",
        "no_top_feature_info": "Top feature bilgisi yok.",
        "no_time_context": "Time context yok.",
        "no_baseline_info": "Baseline deviation bilgisi yok.",
        "system_phase_status": "Sistem Faz Durumu",
        "current_phase": "Mevcut Faz",
        "description": "Açıklama",
        "accounting": "Muhasebe",
        "uptime": "Uptime",
        "event": "Event",
        "duplicate": "Duplicate",
        "parse_fail": "Parse fail",
        "next_phase_label": "Sonraki",
        "progress": "İlerleme",
        "max_phase_reached": "Maksimum faza ulaşıldı",
        "active_layers": "Aktif",
        "inactive_layers": "Pasif",
        "rule_statistics": "Kural İstatistikleri",
        "last_7_days_short": "Son 7 Gün",
        "no_rule_hits_7d": "Son 7 günde hiç tetiklenme yok.",
        "rule_id": "Kural ID",
        "hit": "Hit",
        "avg_score": "Ort.Skor",
        "last_hit": "Son Hit",
        "tactic": "Taktik",
        "fp_warn": "FP?",
        "never_fired_rules": "Son 7 günde hiç tetiklenmeyen kurallar",
        "and_more": "... ve {count} tane daha",
        "top_entities_24h": "Son 24 Saatte En Çok Alert Üreten Entity'ler",
        "alerts": "alert",
        "phase_name_rule_engine": "Kural Motoru",
    },
    "en": {
        "last_n_days": "Last {days} days",
        "last_7_days": "Last 7 days",
        "unknown": "unknown",
        "unspecified": "unspecified",
        "rule_validation_report": "Rule Validation Report",
        "loaded_rules": "Loaded rules",
        "all_rules_valid": "All rules are valid",
        "error_count": "Error count",
        "smoke_test": "Smoke Test",
        "distro": "Distro",
        "unsupported_distro": "Unsupported distro",
        "distro_supported": "Distro supported",
        "db_health_failed": "DB health failed",
        "postgres_connection_ok": "PostgreSQL connection successful",
        "normalize_failed": "Normalize failed",
        "normalize_ok": "Normalize successful",
        "detection_pipeline_ok": "Detection pipeline ran",
        "startup": "Starting",
        "report_title": "SIEM Report",
        "db": "DB",
        "db_url_missing": "PostgreSQL URL missing — startup will fail",
        "db_url_hint_env": "DATABASE_URL=postgresql://user:pass@host:5432/db",
        "db_url_hint_config": "or config.yml: database.url",
        "preflight_config_loaded": "Config file was loaded.",
        "preflight_config_missing": "Config file was not found; continuing with the default/empty configuration.",
        "preflight_config_suggestion": "Verify the presence and permissions of config/config.yml.",
        "preflight_distro_supported": "A supported distro family was detected.",
        "preflight_distro_unsupported": "An unsupported or end-of-life distro was detected.",
        "preflight_distro_suggestion": "Move to a supported family or continue only in read-only inspection mode.",
        "preflight_database_missing": "DATABASE_URL or database.url is not defined.",
        "preflight_database_healthy": "PostgreSQL connectivity and schema health are OK.",
        "preflight_database_degraded": "The PostgreSQL health check returned degraded status.",
        "preflight_database_unreadable": "PostgreSQL health could not be read.",
        "preflight_database_suggestion": "Verify DATABASE_URL, PostgreSQL connectivity, and schema health.",
        "preflight_sources_healthy": "All active sources are reachable.",
        "preflight_sources_degraded": "Some log sources are closed or missing.",
        "preflight_sources_unreadable": "The source health summary could not be read.",
        "preflight_sources_suggestion": "Verify missing log paths or journald access.",
        "preflight_ml_safety_ok": "The ML active layer is operating safely under the audit_only/no-action contract.",
        "preflight_ml_safety_degraded": "The ML safety contract has drifted from the expected read-only/audit-only defaults.",
        "preflight_ml_suggestion": "active_decision_layer.enabled must remain false, mode must remain audit_only, and no_action_contract must remain true.",
        "preflight_ip_blocking_manual_only": "Automatic IP blocking is disabled; only the manual operator workflow is supported.",
        "preflight_ip_suggestion": "Real block/unblock actions must only be used through the explicit manual operator workflow.",
        "preflight_locks_ok": "Read-only security locks are active.",
        "preflight_locks_degraded": "Some security locks are not in the expected state.",
        "preflight_locks_suggestion": "The UI should remain in read-only mode; verify the runtime safety contracts.",
        "preflight_startup_error": "An unexpected error occurred during preflight.",
        "preflight_startup_suggestion": "Verify the config path, Python environment, and core backend imports.",
        "historical_preview_manual_only_message": "Historical log scanning only runs when the user starts a scan from the scan button.",
        "ml_mode_disabled": "Disabled",
        "ml_mode_audit_only": "Audit-only",
        "ml_mode_shadow": "Shadow",
        "ml_mode_unknown": "Unknown",
        "ml_safety_no_autonomous_action": "No autonomous action",
        "ml_training_not_run": "No model has been trained yet.",
        "ml_training_waiting_for_labels": "Waiting for enough high-quality labeled data.",
        "ml_training_status_available": "Training metadata is available.",
        "ml_historical_scan_not_run": "Historical scan has not been run yet. Run it from the CLI when needed.",
        "ml_historical_scan_cli_only": "CLI/manual only",
        "never": "Never",
        "not_available": "not available",
        "llm": "LLM",
        "active": "Active",
        "disabled_config": "Disabled  (config: llm.enabled: false)",
        "enable_hint": "To enable it: llm.enabled: true",
        "missing_api_key": "api_key missing",
        "mock_backend": "Mock backend  (no real API call — test mode)",
        "status_unknown": "status unknown",
        "threat_intel": "Threat Intel",
        "otx": "OTX",
        "disabled_threat_intel": "Disabled  (threat_intel.enabled: false)",
        "free_feeds_otx_active": "{count} free feeds + OTX active",
        "otx_key_missing": "Key missing  ({count} free feeds active)",
        "otx_hint": "For AlienVault OTX: config.yml: threat_intel.otx_api_key  or  env: OTX_API_KEY",
        "free_feeds_active": "{count} free feeds active",
        "distro_label": "Distro",
        "family_label": "family",
        "unsupported": "Unsupported",
        "detect_error": "Detection error",
        "log_sources": "Log Sources",
        "single_source": "single source",
        "active_count": "active",
        "none_enabled_test_mode": "None enabled  → test mode will be used",
        "path_not_defined": "path is not defined — source will not start",
        "file_missing": "file missing",
        "source_disabled_quietly": "the source will remain silently disabled",
        "phase": "Phase",
        "days": "days",
        "hours": "hours",
        "generated_at": "Generated at",
        "since": "Since",
        "total_alerts": "Total Alerts",
        "incident": "Incidents",
        "severity_distribution": "Severity Distribution",
        "severity": "Severity",
        "count": "Count",
        "distribution": "Distribution",
        "hourly_distribution": "Hourly Distribution",
        "ip_reputation": "IP Reputation / AbuseIPDB",
        "reports": "Reports",
        "country": "Country",
        "suggestion_status": "Suggestion Status",
        "no_reputation": "No reputation enrichment available.",
        "alert_explanations": "Alert Explanations",
        "no_alerts_to_explain": "No alerts are available to explain.",
        "explanation_intro_recent": "A short deterministic summary is shown for the last {limit} alerts.",
        "explanation_intro_fallback": "If the report window has no alerts, the most recent alert explanations are shown below.",
        "top_triggered_rules": "Most Triggered Rules",
        "rule": "Rule",
        "recent_incidents": "Recent Incidents",
        "time": "Time",
        "title": "Title",
        "risk_score": "Risk Score",
        "entity": "Entity",
        "status": "Status",
        "no_incidents_yet": "No incidents yet.",
        "most_active_entities": "Most Active Entities",
        "ip_or_user": "IP / User",
        "most_active_users": "Most Active Users",
        "user": "User",
        "why_triggered": "Why was it triggered?",
        "control_recommendations": "Review recommendations",
        "important_evidence_fields": "Important evidence fields",
        "key_evidence": "Key evidence",
        "metadata_missing_short": "Metadata was missing; showing a short fallback explanation.",
        "no_important_fields": "No important event/log fields were available.",
        "manual_validate_context": "Manually validate the related host, user, and process context.",
        "no_top_feature_info": "No top feature information.",
        "no_time_context": "No time context.",
        "no_baseline_info": "No baseline deviation information.",
        "system_phase_status": "System Phase Status",
        "current_phase": "Current Phase",
        "description": "Description",
        "accounting": "Accounting",
        "uptime": "Uptime",
        "event": "Event",
        "duplicate": "Duplicate",
        "parse_fail": "Parse fail",
        "next_phase_label": "Next",
        "progress": "Progress",
        "max_phase_reached": "Maximum phase reached",
        "active_layers": "Active",
        "inactive_layers": "Inactive",
        "rule_statistics": "Rule Statistics",
        "last_7_days_short": "Last 7 Days",
        "no_rule_hits_7d": "No rule hits in the last 7 days.",
        "rule_id": "Rule ID",
        "hit": "Hits",
        "avg_score": "Avg.Score",
        "last_hit": "Last Hit",
        "tactic": "Tactic",
        "fp_warn": "FP?",
        "never_fired_rules": "Rules that never fired in the last 7 days",
        "and_more": "... and {count} more",
        "top_entities_24h": "Entities with the Most Alerts in the Last 24 Hours",
        "alerts": "alerts",
        "phase_name_rule_engine": "Rule Engine",
    },
}


def _normalize_token(value: Any) -> str:
    token = str(value or "").strip()
    if not token:
        return ""
    token = token.replace("-", "_").replace(" ", "_").lower()
    return token


def normalize_language(value: Any, default: str = "tr") -> str:
    fallback = "tr" if _normalize_token(default) == "tr" else "en"
    token = _normalize_token(value)
    if not token:
        return fallback
    return _LANGUAGE_ALIASES.get(token, fallback)


def explanation_catalog(language: Any = "tr") -> Mapping[str, str]:
    resolved = normalize_language(language, default="tr")
    return _EXPLANATION_CATALOG.get(resolved, _EXPLANATION_CATALOG["tr"])


def explanation_text(key: str, language: Any = "tr", **kwargs: Any) -> str:
    catalog = explanation_catalog(language)
    template = catalog.get(key, key)
    if kwargs:
        return str(template).format(**kwargs)
    return str(template)


def system_catalog(language: Any = "tr") -> Mapping[str, str]:
    resolved = normalize_language(language, default="tr")
    return _SYSTEM_CATALOG.get(resolved, _SYSTEM_CATALOG["tr"])


def system_text(key: str, language: Any = "tr", **kwargs: Any) -> str:
    catalog = system_catalog(language)
    template = catalog.get(key, key)
    if kwargs:
        return str(template).format(**kwargs)
    return str(template)


def _mapping_value(payload: Any, key: str) -> Any:
    if isinstance(payload, Mapping):
        return payload.get(key)
    return None


def _config_language(config: Any) -> Any:
    if isinstance(config, str):
        return config
    if not isinstance(config, Mapping):
        return None
    root_language = _mapping_value(config, "language")
    if root_language not in (None, ""):
        return root_language
    llm_cfg = _mapping_value(config, "llm")
    if isinstance(llm_cfg, Mapping):
        return _mapping_value(llm_cfg, "language")
    return None


def _env_language(env: Any) -> Any:
    if isinstance(env, str):
        return env
    if not isinstance(env, Mapping):
        return None
    for key in ("AEGIS_LANGUAGE", "LLM_LANGUAGE", "language"):
        value = env.get(key)
        if value not in (None, ""):
            return value
    return None


def resolve_language(
    explicit: Any = None,
    ui_language: Any = None,
    env: Any = None,
    config: Any = None,
    default: str = "tr",
) -> str:
    fallback = normalize_language(default, default="tr")
    for candidate in (
        explicit,
        ui_language,
        _env_language(env),
        _config_language(config),
    ):
        if candidate not in (None, ""):
            return normalize_language(candidate, default=fallback)
    return fallback
